### ISSUE TITLE
I want to ask some questions

### ISSUE THREAD

**Issue by mjm212** [cts198859/deeprl_signal_control#14]
Hello, thank you very much for your paper (Multi-Agent Deep Reinforcement Learning for Large-Scale Traffic Signal Control) and let me learn a lot. 
After reading the experiment, I downloaded your code on git and ran it. In the results of my run, the reward of 5x5 is not good as the plot of this paper. Is this situation caused by parameters or seed?
And I test the real_net, the reward is about twice of the ma2c_real_train_reward.csv in your git-project.  Is this situation caused by flow_rate ?
I'm looking forward to your reply.
Best wishes,

**Comment by cts198859** [comment]
Thanks for pointing this out. There were a few recent changes on master after the paper publish, which might hurt the reproducibility. To re-generate paper results, please go to commit 6b12202: https://github.com/cts198859/deeprl_signal_control/tree/6b1220247fb90cfe6c7d6976bb8cc0ed6713a888, and use sumo 0.32.0.

**Comment by mjm212** [comment]
thank you

**Comment by mjm212** [comment]
If the version of sumo I use is different, will it affect the results of the final experiment?

**Comment by cts198859** [comment]
Yes, many factors can affect the RL results in general. I have updated the README to address the reproducibility. The general idea is that rather than reproducing the same paper results, your conclusion should always be valid as far as the evaluation is fair across agents. For example, if your algorithm outperforms MA2C with >= 50 evaluation seeds using the latest master, you can claim it.
