### ISSUE TITLE
Unable to create listening socket: Address already in use

### ISSUE THREAD

**Issue by Vonisoa** [cts198859/deeprl_signal_control#16]
I run the train.py using the large_grid and sumo version 1.3.1 but I got the following error :

> Error: tcpip::Socket::accept() Unable to create listening socket: Address already in use
> Quitting (on error).

Does anyone know how to avoid this?

**Comment by cts198859** [comment]
This may because your machine is slow so it is not able to completely release the SUMO port after the previous episode ends when the next episode tries to reuse the same port. Please try to increase the sleep time between two episodes. 
e.g. adding time.sleep(2) after self.sim.close() in env.terminate(self).

**Comment by Vonisoa** [comment]
Ok, I will try your advice and tell you if it is working. Thank you

**Comment by Vonisoa** [comment]
Thank you, It is working.
