### ISSUE TITLE
Giving a minimum green duration.

### ISSUE THREAD

**Issue by parksanha** [cts198859/deeprl_signal_control#29]
Hello.

I have another question.

I want to give the traffic lights a minimum green duration.

How can I do it? Can you help me?

**Comment by cts198859** [comment]
This is tricky. 1) the minimum green duration must be a multiple of step size, i.e., control_interval_sec. 2) the easiest way to ensure this is to inset post-RL logic in env:step() https://github.com/cts198859/deeprl_signal_control/blob/c3cadbd088a3f6946ecba667fd07cbd689947d32/envs/env.py#L566. You can use the enforced yellow time logic as reference, basically you need to memorize how many "green" steps have been observed so far.

**Comment by parksanha** [comment]
I understood the explanation for 1).

But I'm not sure how to do 2).

Could you please explain in more detail?

**Comment by cts198859** [comment]
basically you do not restrict what RL learns, instead enforce your constraint when you simulate the step, by adjusting RL decision if it violates the constraint. e.g., RL:GGR->Actual:GGG if you need a minimum green duration of 3 MDP steps. Then RL will learn your enforcement automatically as part of env since the transition depends on actual actions.
