### ISSUE TITLE
How many steps does the neural network's lstm look past?

### ISSUE THREAD

**Issue by parksanha** [cts198859/deeprl_signal_control#31]
Hello.

How many steps does the neural network's lstm look past?

**Comment by cts198859** [comment]
Good question. We use stateful LSTM, and instead of fixed number of look-back steps, we reset the memory state at beginning of each training/testing episode:
https://github.com/cts198859/deeprl_signal_control/blob/c3cadbd088a3f6946ecba667fd07cbd689947d32/utils.py#L281
So you can think it looks back to the very initial MDP state and the memory can be as long as T.

**Comment by parksanha** [comment]
Thank you for the reply.

As you say,

in a certain episode,

at time t,(t <= T)

lstm receives the states of s_0, s_1, ..., s_t-1, s_t sequentially, right?

**Comment by cts198859** [comment]
Not exactly: it only receives s_t, but h_t = f(h_{t-1}, s_t), so h_t implicitly carries past memory. h is maintained internally in LSTM.

**Comment by parksanha** [comment]
As a result,

Does that mean lstm observes all the past(the past is stored in h_{t-1}) and current state(s_t) in an episode and then acts on it?

**Comment by cts198859** [comment]
At high-level, yes. Please check the code and LSTM reference for details.

**Comment by parksanha** [comment]
Thanks~
